### ISSUE TITLE
Get receipt by id

### ISSUE THREAD

**Issue by nixv2** [grempe/tierion#1]
i was wandering if there is a way to get the receipt by it's id, i see the "receipt" method but is expecting a Tierion::HashApi::HashItem object.
what about a more direct way to get the receipt by its id, something like this: receipt('receipt_id') and not the Tierion::HashApi::HashItem object.

Thanks...

**Comment by grempe** [comment]
Hi, I thought about this, but one of the things that I liked about the current implementation is that by having a fully formed HashItem object, with the target hash, timestamp, receipt ID, is that you can verify that the merkle proof of the receipt returned actually works with the hash that was originally stored in the HashItem. When you get a receipt now, passing in a HashItem object, it
does that for you automatically.

You can manually create a new HashItem with something like:

```
hi = Tierion::HashApi::HashItem.new(id: hash_item_id, timestamp: Time.now.utc.to_i, hash: obj_hash)
```

I suppose there could be an API like you suggested, but it should pass in both a receipt ID and the target hash for validation and to insure integrity.  Otherwise, you would not really know for sure that Tierion returned the correct receipt for you!

I'll add that now.

**Comment by grempe** [comment]
ok, I added it and pushed it to git. You can use it like:

```
t.receipt_from_id_and_hash('57a8db8478c3b7da3450fd54', 'a65f7dfa6fd4a966ac0989342f70a2ef465893ea45a8c7b802c898a53de953df')
```

Cheers!

**Comment by grempe** [comment]
Version 1.2.0 release pushed to Rubygems and Github.

https://github.com/grempe/tierion/releases/tag/v1.2.0
